/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2018-05-07 11:12:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.error;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class error404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>error</title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t    *{font-family:\"Lucida Grande\",\"Helvetica\",\"Arial\",\"Verdana\",\"sans-serif\";font-weight:normal;}\r\n");
      out.write("\t    h1{color:#343434;font-weight:bold;}\r\n");
      out.write("\t    h2{color:#555555;}\r\n");
      out.write("\t    p{color:#999999;}\r\n");
      out.write("\t    html{height:100%;width:100%;margin:0;padding:0;}\r\n");
      out.write("\t    body{height:100%;width:100%;margin:0;padding:0;}\r\n");
      out.write("\t    table{border-collapse:collapse; }\r\n");
      out.write("\t    a{color:#08c;}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<table width=\"100%\" height=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"background-color:#F3F4F5;\">\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t        <td>\r\n");
      out.write("\t\t            <table width=\"400\" height=\"250\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"background-color:#fff;\">\r\n");
      out.write("\t\t                <tr>\r\n");
      out.write("\t\t                    <td>\r\n");
      out.write("\t\t                        <table width=\"400\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t                            <tr>\r\n");
      out.write("\t\t                                <td>\r\n");
      out.write("\t\t                                    <table width=\"400\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t                                        <tr align=\"center\">\r\n");
      out.write("\t\t                                            <td width=\"200\"><img src=\"../../../resources/image/error/error.png\"><h2>죄송합니다.</h2></td>\r\n");
      out.write("\t\t                                        </tr>\r\n");
      out.write("\t\t                                        <tr>\r\n");
      out.write("\t\t                                            <td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t                                                <p>요청하신 페이지를 찾을 수 없습니다.</p>\r\n");
      out.write("\t\t                                                <p><a href=\"/loginFrame.do\">로그인 화면</a>으로 돌아가기</p>\r\n");
      out.write("\t\t                                            </td>\r\n");
      out.write("\t\t                                        </tr>\r\n");
      out.write("\t\t                                    </table>\r\n");
      out.write("\t\t                                </td>\r\n");
      out.write("\t\t                            </tr>\r\n");
      out.write("\t\t                        </table>\r\n");
      out.write("\t\t                    </td>\r\n");
      out.write("\t\t                </tr>\r\n");
      out.write("\t\t            </table>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
